# GET http://localhost:3000/

# ###
# GET http://localhost:8000/users  
# ###
# GET http://localhost:3000/category


GET http://localhost:3000/menu_item/2
###
GET http://localhost:3000/users

###
DELETE   http://localhost:3000/orders/1
Authorization: 
###
DELETE http://localhost:3000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwaXRheiIsInJvbGUiOiJkcml2ZXIiLCJleHAiOjE3MTgxNDMzMzN9.R0lTOQhUm2ElkWGU0D2LbIBlZYXo_pWugN48nkYuGTQ

###
GET http://localhost:3000/category
###
GET http://localhost:3000/city/2
###
GET http://localhost:3000/driver/1
###
GET http://localhost:3000/restaurant/1
###
GET http://localhost:3000/address
###
GET http://localhost:3000/restaurant_owner

###
GET http://localhost:3000/restaurant_owner/1
###insert
POST http://localhost:3000/auth
Content-Type: application/json

{
  "username": "Anto",
  "userId": 2,
  "password": "pass"
}

###
DELETE http://localhost:3000/restaurant_owner/1

###search
GET http://localhost:3000/driver


###GET Category
GET http://localhost:3000/category
Authorization: 

Content-Type: application/json
{
  "id":3
}

###DELETE a category
DELETE http://localhost:3000/category/3
###
### Creating a category
POST http://localhost:3000/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKYXkiLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODE5NTYyOH0.aw-h6VtCw4N4eLJRyh46HpceyY64mg3l8S8d1sa3bNI

{
  "name": "Smoothie"
}

###CITY
DELETE http://localhost:3000/city/13
###

### create a city
POST http://localhost:3000/city
Content-Type: application/json

{
  "name": "Kisumu",
  "state_id": 1
}

###DELETE Driver
DELETE http://localhost:3000/driver/1
Authorization: 

### UPDATE Driver
PUT http://localhost:3000/driver/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwaXRheiIsInJvbGUiOiJkcml2ZXIiLCJleHAiOjE3MTgyNzkwNDl9.B612jWopU0oyhfZN1yHfEOT5B26BjSFh41VN14Xz9W0

{
  "car_make": "Toyota",
  "car_model": "Corolla",
  "car_year": 2020,
  "user_id": 1,
  "online": true,
  "delivering": false
}

###DELETE menu_item
DELETE http://localhost:3000/menu_item/1

###UPDATE
PUT http://localhost:3000/menu_item/1
Content-Type: application/json

{
  "name": "Berry Smoothie",
  "description": "A refreshing smoothie made with berries",
  "price": 5.99,
  "category_id": 3
}

###DELETE order
DELETE http://localhost:3000/orders/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEYXZ5Iiwicm9sZSI6InJlc3RhdXJhbnRfb3duZXIiLCJleHAiOjE3MTgxNDQwNjZ9.Z2yyawLVyQDienauW9ALcWtzab10srau61nxkoNX7Ms

###DELETE restaurant
DELETE http://localhost:3000/restaurant/3

###
# Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Jay",
  "userId": 4,
  "password": "pass",
  "role": "user"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "pitaz",
  "password": "pass"
}

###Token
GET http://localhost:3000/city/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwaXRheiIsInJvbGUiOiJkcml2ZXIiLCJleHAiOjE3MTgyOTcxNzR9.eAKKYf9BcGhtGc2fAwGoGTeRTIDXCeL10jVNBI8MXPw
###



#insert Address
POST http://localhost:3000/address
Content-Type: application/json

{
   "street_address_1": "Embu01",
   "street_address_2": "Embu02",
   "zip_code": "Embu0102",
   "delivery_instructions": "Leave package at front door",
   "user_id": 2,
   "city_id": 2
}

###
#get driver
GET http://localhost:3000/driver/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwaXRheiIsInJvbGUiOiJkcml2ZXIiLCJleHAiOjE3MTgyODcwMzF9.p_3WiACOwsp6GLI6-TNlzQ_ZzdS0GA6HT1fzwtJ4XNQ

###//get comment only from coments ~user
GET http://localhost:3000/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKYXkiLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODI4NTcyNn0.gPwbnymeAQezS6w2vsIOXUQVV3OV2Tlq-kx0GRK2oYw





